### PR TITLE
Improvements to the `README` file

### PR DESCRIPTION
**Pull request by cr2007**
This PR adds better, improved changes to the `README.md` file, some general formatting changes to make it appear better for the user.

- Adds a proper Index to provide the user with an eagle's eye view of the documentation and the repository as a whole
- Adds a hyperlink support to certain files provided within the file
- Formats the HTML code at the very top of the file
- Adds a hyperlink in the coders(hq) logo to the [website](https://ai.gov.ae/codershq/) directly

Feel free to add any changes of your own in this PR if needed.

Good Day,
[@cr2007](https://github.com/cr2007)

### CODE REVIEW

**Comment by cr2007** [comment]
Adds `alt`, `title` attributes to the `` tags at the top of the `README.md` file
Adds accessibility support by adding these 2 attributes

**Comment by cr2007** [comment]
Hey Coders-HQ Team,

This is a small PR which improved the layout of the `README.md` file on this repository.

Do have a look into it and see if there are any changes (if needed) from your side.

Regards,
@cr2007

**Comment by cr2007** [comment]
@Musab0 @ralsuwaidi

**Review by husayngokal — CHANGES_REQUESTED** [review]
1. The coders(hq) logo and title are not aligned anymore
2. Redirect the "License MIT" button to the license file in the repository itself
3. The Discord Invite link expired, use this one instead: https://discord.gg/X3vZZxK3KQ
4. All of the titles in "Index" don't have URLs
5. "Note" looks a bit weird in the "Getting Up and Running Locally With Docker" section
6. The punctuation in "Prerequisites" is off for each point
7. Add my picture in Contributors now that I helped out :)

Husayn Gokal

Note: I didn't have a look at any of the technical updates, so I hope you're updated instructions don't break anything 🤞

**Pull request merged**
